const BASE_URL = import.meta.env.BASE_URL;

const cards = [
    // Left side (top row)
    {
        id: 1,
        title: 'Millie the Witch',
        description:
            'An exploration of time-based visual language — how form travels, morphs, and communicates energy across frames.',
        image: `${BASE_URL}images/motion/millie_the_witch/Card.png`,
        video: `${BASE_URL}videos/motion/milie_the_witch/witch_short.MP4`,
        category: 'motion',
        group: 'millie',
        year: '2024',
        role: 'Motion Designer',
        skills: 'Animation, Illustration, Storyboarding',
        team: 'Solo',
        size: 'tall',
        side: 'left',
        related: [9],
    },
    {
        id: 2,
        title: 'Hold Your Pee: Fishes',
        description:
            'A fun, fast-paced card game where players compete to avoid breaking the seal. Features minimalist two-colour illustrations like this Fishes card.',
        image: `${BASE_URL}images/graphic/hold_your_pee/fishes.svg`,
        group: 'hold_your_pee',
        category: 'graphic',
        categoryLabel: 'Card Game',
        year: '2025',
        size: 'tall',
        side: 'left',
    },
    // Right side (top row)
    {
        id: 3,
        title: 'Agent Cocoa',
        description:
            'From user research and journey mapping through wireframes, prototypes, and a final high-fidelity design system built for calm, accessible experience.',
        image: `${BASE_URL}images/uiux/agent_cocoa/Card.png`,
        category: 'uiux',
        group: 'agent_cocoa',
        year: '2024',
        role: 'Product Designer',
        skills: 'UI/UX, Wireframing, Prototyping',
        team: 'Aayushi Singh',
        expandTarget: 800,
        size: 'ultraWide',
        side: 'right',
        related: [8],
    },
    {
        id: 4,
        title: 'Hold Your Pee: Cats',
        description:
            'A cohesive visual language for the quick-paced card game, highlighting dynamic typography.',
        image: `${BASE_URL}images/graphic/hold_your_pee/Cats.svg`,
        category: 'graphic',
        categoryLabel: 'Card Game',
        group: 'hold_your_pee',
        year: '2025',
        size: 'tall',
        side: 'right',
    },
    {
        id: 5,
        title: 'Hold Your Pee: Geisha',
        description:
            'Minimalist two-colour illustrations for a rapidly engaging card game experience.',
        image: `${BASE_URL}images/graphic/hold_your_pee/Geisha.svg`,
        category: 'graphic',
        categoryLabel: 'Card Game',
        group: 'hold_your_pee',
        year: '2025',
        size: 'tall',
        side: 'right',
    },
    // Bottom row
    {
        id: 6,
        title: 'Hold Your Pee: Kabuki',
        description:
            'Kabuki drink card illustration highlighting striking linework and strict layout structure.',
        image: `${BASE_URL}images/graphic/hold_your_pee/kabuki.svg`,
        category: 'graphic',
        categoryLabel: 'Card Game',
        group: 'hold_your_pee',
        year: '2025',
        size: 'tall',
        side: 'bottom',
    },
    {
        id: 7,
        title: 'Hold Your Pee: Frog',
        description:
            'Playful green-themed drink card for the Hold Your Pee collection.',
        image: `${BASE_URL}images/graphic/hold_your_pee/frog.svg`,
        category: 'graphic',
        categoryLabel: 'Card Game',
        group: 'hold_your_pee',
        year: '2025',
        size: 'tall',
        side: 'bottom',
    },
    {
        id: 8,
        title: 'Agent Cocoa Logo',
        description:
            'The core visual identity and typographic mark for the Agent Cocoa wellness app, emphasizing warmth.',
        image: `${BASE_URL}images/visual/agent_cocoa/agentcocoa.svg`,
        category: 'visual',
        group: 'agent_cocoa',
        year: '2024',
        role: 'Brand Designer',
        skills: 'Typography, Logo Design',
        team: 'Aayushi Singh',
        size: 'wide',
        side: 'bottom',
        related: [3],
    },
    {
        id: 9,
        title: 'Millie Logo',
        description:
            'Wordmark and brand identity exploration for the Millie the Witch animated concept.',
        image: `${BASE_URL}images/visual/agent_cocoa/millie_logo.jpg`,
        category: 'visual',
        group: 'millie',
        year: '2024',
        role: 'Brand Designer',
        skills: 'Identity, Lettering',
        team: 'Solo',
        size: 'default',
        side: 'bottom',
        related: [1],
    },
    // --- SECONDARY GALLERY IMAGES (No 'side' property so they are hidden from the masonry grid) ---
    {
        id: 10,
        title: 'Millie Animation Frame',
        image: `${BASE_URL}images/motion/millie_the_witch/animation.png`,
        category: 'motion',
        group: 'millie',
    },
    {
        id: 11,
        title: 'Millie Character Design',
        image: `${BASE_URL}images/motion/millie_the_witch/character.PNG`,
        category: 'motion',
        group: 'millie',
    },
    {
        id: 12,
        title: 'Millie Flowboard',
        image: `${BASE_URL}images/motion/millie_the_witch/flow.PNG`,
        category: 'motion',
        group: 'millie',
    },
    {
        id: 13,
        title: 'Agent Cocoa Home',
        image: `${BASE_URL}images/uiux/agent_cocoa/Home.png`,
        category: 'uiux',
        group: 'agent_cocoa',
    },
    {
        id: 14,
        title: 'Agent Cocoa Features',
        image: `${BASE_URL}images/uiux/agent_cocoa/Feature.png`,
        category: 'uiux',
        group: 'agent_cocoa',
    },
    {
        id: 15,
        title: 'Agent Cocoa How it Works',
        image: `${BASE_URL}images/uiux/agent_cocoa/how-it-works.png`,
        category: 'uiux',
        group: 'agent_cocoa',
    },
    {
        id: 16,
        title: 'Agent Cocoa Feature Detail',
        image: `${BASE_URL}images/uiux/agent_cocoa/feature-detail.png`,
        category: 'uiux',
        group: 'agent_cocoa',
    },
    {
        id: 17,
        title: 'Agent Cocoa Pricing',
        image: `${BASE_URL}images/uiux/agent_cocoa/pricing.png`,
        category: 'uiux',
        group: 'agent_cocoa',
    },
]

export default cards
